const types = {
  EVENTS_INDEX: 'EVENTS_INDEX',
  EVENT_SHOW: 'EVENT_SHOW',
  EVENT_NEW: 'EVENT_NEW',
  EVENT_CREATE: 'EVENT_CREATE',
  EVENT_EDIT: 'EVENT_EDIT',
  EVENT_UPDATE:'EVENT_UPDATE',
  EVENT_DELETE:'EVENT_DELETE'
}

export default types